login:
    pattern:   /login
    defaults:  { _controller: IntaroSecurityBundle:Security:login }

login_check:
    pattern:   /login_check
    
IntaroBookBundle:
    resource: "@IntaroBookBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
