IntaroBookBundle_homepage:
    pattern:  /
    defaults: { _controller: IntaroBookBundle:Default:index }
    
IntaroBookBundle_book:
    resource: "@IntaroBookBundle/Resources/config/routing/book.yml"
    prefix:   /books