parameters:
#    intaro_security.example.class: Intaro\SecurityBundle\Example

services:
#    intaro_security.example:
#        class: %intaro_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
